[package]
name = "usysconf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "1.3.3", features = ["i128"] }
clap = "4.4.2"
ion-rs = "0.18.1"
ion-schema = "0.9.1"
